pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: '首页'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
  # home config
  en-us:
   title: 'home'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
 resource:
  # 首页配置
  zh-cn:
   title: '资源'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
  # home config
  en-us:
   title: 'resource'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
 community:
  # 社区页配置
  zh-cn:
   title: '社区'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'community'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
 blog:
  # 博客列表页配置
  zh-cn:
   title: '博客'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
  en-us:
   # blog list page config
   title: 'blog'
   keywords: 'jcohy，docs'
   description: 'jcohy-docs'
